version: "3.8"

services:

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: bajrami27
      POSTGRES_DB: slackbot_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama
    ports:
      - "11435:11434"
    volumes:
      - ollama_storage:/root/.ollama

  bot:
    build: .
    depends_on:
      - db
      - ollama
    env_file:
      - .env
    ports:
      - "8000:8000"

volumes:
  postgres_data:
  ollama_storage: